# Aufgabe 10: 3-SAT Problem

In [1744]:
import numpy as np

rng = np.random.default_rng()

#Klauselmenge = rng.integers(size=(25,3), low=-20, high=21)
Klauselmenge = []
for i in range(25):
    numLiterale = rng.integers(low=1, high=4)
    if numLiterale == 1:
        Klauselmenge.append([rng.choice(np.concatenate((np.arange(-20, 0), np.arange(1, 21)))), 0, 0])
    if numLiterale == 2:
        Klauselmenge.append([rng.choice(np.concatenate((np.arange(-20, 0), np.arange(1, 21)))), rng.choice(np.concatenate((np.arange(-20, 0), np.arange(1, 21)))), 0])
    if numLiterale == 3:
        Klauselmenge.append([rng.choice(np.concatenate((np.arange(-20, 0), np.arange(1, 21)))), rng.choice(np.concatenate((np.arange(-20, 0), np.arange(1, 21)))), rng.choice(np.concatenate((np.arange(-20, 0), np.arange(1, 21))))])

print(Klauselmenge)


[[8, 13, 14], [9, 6, 5], [5, 0, 0], [-14, 20, 10], [-17, 13, 0], [17, 0, 0], [-1, 0, 0], [4, 12, 0], [-13, 8, 0], [13, 15, 0], [-14, -17, 6], [-11, 0, 0], [18, 0, 0], [-3, -11, -20], [15, 20, 0], [-5, 7, -6], [-18, 4, 12], [-1, -18, 0], [-13, 0, 0], [-19, -11, 0], [14, 0, 0], [-8, 5, 0], [6, 15, 0], [14, 2, 3], [8, 11, -8]]


In [1745]:
def InitPopulation(numIndividuen, numVariablen):
    initPopulation = rng.integers(size=(numIndividuen, numVariablen + 1), low=0, high=2)
    for individuum in initPopulation:
        individuum[0] = 1
    return initPopulation

In [1746]:
startPopulation = InitPopulation(100, 20)
print(startPopulation)

[[1 0 1 ... 0 1 1]
 [1 0 1 ... 0 0 1]
 [1 0 0 ... 1 0 1]
 ...
 [1 0 0 ... 1 1 1]
 [1 0 0 ... 1 1 1]
 [1 1 0 ... 1 1 1]]


In [1747]:
def sortPopulation(population):
    bewertung = {}
    for i, individuum in enumerate(population):
        erfüllteKlauseln = 0
        for klausel in Klauselmenge:
            for variable in klausel:
                if variable > 0 and individuum[variable] == 1:
                    erfüllteKlauseln = erfüllteKlauseln + 1
                    break
                elif variable < 0 and individuum[-1 * variable] == 0:
                    erfüllteKlauseln = erfüllteKlauseln + 1
                    break
        bewertung[i] = erfüllteKlauseln

    sortierteIndividuen = dict(sorted(bewertung.items(), key=lambda item: item[1]))

    return sortierteIndividuen


In [1748]:
def Selektion(sortedPopulation, population):
    selected = []
    for i in range(100):
        individuum = population[list(sortedPopulation.keys())[99-i] - 1]
        selected.append(individuum)

    return selected

    

In [1749]:
def Mutation(sortedPopulation, population):
    mutatedPopulation = []
    for i in range(20):
        individuum = population[list(sortedPopulation.keys())[99-i] - 1]
        mutationSpot = rng.integers(low=1, high=21)
        individuum[mutationSpot] = 1 if individuum[mutationSpot] == 0 else 0
        mutatedPopulation.append(individuum)

    return mutatedPopulation
        

In [1750]:
def Rekombination(sortedPopulation, population):
    recombinedPopulation = []
    for i in range(15):
        individuum1 = np.array_split(population[list(sortedPopulation.keys())[99-i] - 1], 2)
        individuum2 = np.array_split(population[list(sortedPopulation.keys())[rng.integers(low=1, high=21)] - 1], 2)

        new1 = np.concatenate((individuum1[0], individuum2[1]))
        new2 = np.concatenate((individuum2[0], individuum1[1]))

        recombinedPopulation.append(new1)
        recombinedPopulation.append(new2)
        
    return recombinedPopulation


In [1751]:
def createNewRandom():
    newRandoms = rng.integers(size=(30, 20 + 1), low=0, high=2)
    for individuum in newRandoms:
        individuum[0] = 1
        
    return newRandoms

In [1752]:
def Evolution(iterations, startPopulation):
    population = startPopulation
    for i in range(iterations):
        sortedPopulation = sortPopulation(population)
        print(list(sortedPopulation.values())[99])

        selektion = Selektion(sortedPopulation, population)
        #mutation = Mutation(sortedPopulation, population)
        #rekombination = Rekombination(sortedPopulation, population)
        newRandoms = createNewRandom()
        #newPopulation = np.concatenate((selektion, newRandom),  axis=0)
        #print(selektion)
        print(newRandoms)
        newPopulation = np.concatenate((selektion, newRandoms))
        #print(newPopulation)

        population = newPopulation

        
        

        
        
Evolution(1, startPopulation)

23
[[1 1 0 0 0 0 1 1 1 0 1 1 1 1 0 1 0 0 1 0 0]
 [1 1 0 1 1 1 1 0 1 0 0 0 1 1 0 0 0 0 1 1 0]
 [1 0 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1 0 0 1]
 [1 0 1 0 0 0 0 1 0 0 1 0 1 1 1 0 0 1 0 1 0]
 [1 1 1 0 0 1 0 1 1 0 1 1 0 1 1 1 0 0 1 0 1]
 [1 0 0 1 0 1 1 1 1 1 0 1 0 0 1 0 0 1 1 1 1]
 [1 1 1 0 0 0 0 1 1 0 1 1 1 1 0 1 1 0 0 0 1]
 [1 0 1 0 0 1 0 0 1 0 1 1 0 1 0 1 0 0 0 1 0]
 [1 0 0 1 0 0 1 0 0 1 0 1 0 0 0 1 1 0 1 1 1]
 [1 1 1 0 0 0 1 0 1 0 1 0 0 1 0 0 0 0 1 1 0]
 [1 0 1 1 0 0 0 0 0 0 1 0 1 1 0 1 1 1 1 1 0]
 [1 1 0 1 1 0 0 0 0 0 0 1 1 1 1 1 1 0 0 1 0]
 [1 1 0 1 0 0 1 1 0 1 0 0 1 1 0 1 1 1 1 1 1]
 [1 1 1 0 1 1 1 1 0 1 0 1 0 1 1 0 1 1 1 1 0]
 [1 0 0 1 1 1 1 0 0 1 0 0 0 1 1 0 1 1 1 0 1]
 [1 1 1 1 1 0 1 0 0 0 0 0 0 1 1 1 0 0 1 1 1]
 [1 1 0 0 1 1 0 0 0 1 1 0 1 0 1 1 0 0 0 0 1]
 [1 1 0 1 1 1 1 1 0 0 0 1 1 1 0 0 1 0 1 0 1]
 [1 0 1 0 1 0 0 0 0 1 1 1 0 1 1 1 0 1 1 1 1]
 [1 1 0 1 0 0 0 1 0 0 0 0 1 1 0 1 0 0 0 0 1]
 [1 1 0 1 1 0 1 1 1 1 1 1 1 0 1 1 0 0 1 0 1]
 [1 1 1 0 0 1 1 1 0 1 0 1 1 1 0 0 0 0 0 1 1]
 [1 1 0